apiVersion: apis.kcp.dev/v1alpha1
kind: APIResourceSchema
metadata:
  creationTimestamp: null
  name: v221103-4c8e4067.apps.appstudio.dev
spec:
  group: appstudio.dev
  names:
    kind: App
    listKind: AppList
    plural: apps
    singular: apps
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      description: Apps are made in AppStudio
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: AppSpec holds the desired state of the Pipeline.
          properties:
            intent:
              type: string
          type: object
        status:
          description: AppStatus communicates the observed state of the Pipeline.
          properties:
            result:
              type: string
          type: object
      type: object
    served: true
    storage: true
    subresources:
      status: {}
