# permissions for end users to view entitlements.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: entitlement-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: entitlment-crd
    app.kubernetes.io/part-of: entitlment-crd
    app.kubernetes.io/managed-by: kustomize
  name: entitlement-viewer-role
rules:
- apiGroups:
  - authz.authz
  resources:
  - entitlements
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authz.authz
  resources:
  - entitlements/status
  verbs:
  - get
