name: SpiceDB seatdemo Build & Test
on:
  push:
    branches:
      - 'main'
    paths:
      - 'engine_eval/zanzibar/authzed/seatdemo/**'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./engine_eval/zanzibar/authzed/seatdemo/src
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
          cache-dependency-path: "./engine_eval/zanzibar/authzed/seatdemo/src"
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
  push-to-registry:
    needs: build_and_run_tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          repository: ${{ secrets.REGISTRY_NAMESPACE }}/${{ env.image_name }}
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:engine_eval/zanzibar/authzed/seatdemo/src"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/dguhr/test:latest