name: SpiceDB seatdemo Build & Test
on:
  push:
    branches:
      - 'main'
    paths:
      - 'engine_eval/zanzibar/authzed/seatdemo/**'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./engine_eval/zanzibar/authzed/seatdemo/src
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true
          cache-dependency-path: "./engine_eval/zanzibar/authzed/seatdemo/src"
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test ./...
  push-to-registry:
    #needs: build_and_run_tests
    runs-on: ubuntu-latest
    steps:
      -
        name: Set short git commit SHA
        id: vars
        run: |
            calculatedSha=$(git rev-parse --short=7 ${{ github.sha }})
            echo "::set-output name=short_sha::$calculatedSha"

      - name: Confirm git commit SHA output
        run: echo ${{ steps.vars.outputs.short_sha }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Quay
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:engine_eval/zanzibar/authzed/seatdemo/src"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            quay.io/dguhr/test:latest,
            quay.io/dguhr/test:${{ steps.vars.outputs.short_sha }},
            quay.io/dguhr/test:${{ github.run_id }}-${{ github.run_attempt	}}
            quay.io/dguhr/test:${{ steps.vars.outputs.short_sha }}-${{ github.run_id }}-${{ github.run_attempt	}}