name: SpiceDB Testcontainers experiment Build
on:
  push:
    paths:
      - 'engine_eval/zanzibar/authzed/**'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_run_tests:
    runs-on: ubuntu-latest
    env:
      working-directory: ./engine_eval/zanzibar/authzed/int-test-setup
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test
